[package]
name = "gui"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.33.2"
egui = "0.33.2"
rfd = "0.15.4"
log_engine = { path = "../log_engine" }
regex = "1.12.2"
clap = { version = "4.5.53", features = ["derive"] }
